
# Hierarchical settings, can be extended/overridden at various level
"settings":
  "rst2pdf_conf_file": "themes/rst2pdf.conf"
  "rst2pdf_extra_args": "--stylesheets=layout_large_fonts"  # E.g. --stylesheets=with_cover_and_background

# Hierarchical jinja2 variables, can be extended/overridden at various level
"variables":
  "game_title": "Le Dernier Vœu des Druides"
  "game_subtitle": "Un jeu-mystère en 2h pour tout public"

"summary_generation":
  "game_facts_template": "summaries/game_facts_summary.txt"
  "game_facts_destination": "summaries/game_facts_summary"

  "game_symbols_template": "summaries/game_symbols_summary.txt"
  "game_symbols_destination": "summaries/game_symbols_summary"

  "game_items_template": "summaries/game_items_summary.txt"
  "game_items_destination": "summaries/game_items_summary"

"inventory_generation":
  "main_inventory":
    "inventory_data": "inventories/game_inventory_data.yaml"

    "inventory_per_section_template": "inventories/game_inventory_per_section.txt"
    "inventory_per_section_destination": "inventories/main_inventory_per_section"

    "inventory_per_crate_template": "inventories/game_inventory_per_crate.txt"
    "inventory_per_crate_destination": "inventories/main_inventory_per_crate"

"document_generation":
  "game_paper_clues":
    "document_source": "documents/clues_for_game.odt"
    "document_splitting":
      - ["symboles_de_mythologie_gauloise", 1]
      - ["lettre_medievale_sur_runes_du_cromlech", 1]

"sheet_generation":

  "variables":

  "sheets":
    "gamemaster_manual":
      "settings":
        "rst2pdf_extra_args": "--stylesheets=layout_large_fonts,with_cover_and_background"
      "full_sheet": "gamemaster_manual.rst"
    "déroulement_du_jeu":
      "full_sheet": "déroulement_du_jeu.rst"

  "groups":

    "non_playable_characters":
      "variables":

      "sheets":
        "conservateur_du_musee":
          "full_sheet":
            - "characters/conservateur_du_musee.rst"
        "guide_du_musee":
          "full_sheet":
            - "characters/guide_du_musee.rst"
        "etudiant_reporter":
          "full_sheet":
            - "characters/etudiant_reporter.rst"
        "spectre_du_druide":
          "full_sheet":
            - "characters/spectre_du_druide.rst"

    "playable_characters":
      "sheets":
        "detectives_du_paranormal":
          "full_sheet":
            - "characters/detectives_du_paranormal.rst"

    "ingame_clues":
      "variables": {}
      "sheets":
        "rapports_de_police":
          "full_sheet":
            - "documents/rapports_de_police.rst"
        "derniere_bataille_des_gaulois":
          "full_sheet":
            - "documents/derniere_bataille_des_gaulois.rst"
        "article_sur_le_cromlech_lyonnais":
          "full_sheet":
            - "documents/article_sur_le_cromlech_lyonnais.rst"
        "description_des_artefacts_antiques":
          "full_sheet":
            - "documents/description_des_artefacts_antiques.rst"
